# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-10 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('placetypeid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('visitdate', models.DateTimeField(verbose_name='Date of Visit')),
                ('textfield', models.TextField()),
                ('placetypeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abeona.PlaceType')),
            ],
        ),
    ]
