# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-10 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abeona', '0002_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='placetype',
            name='name',
            field=models.CharField(default='<Place Name>', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewedby',
            field=models.CharField(max_length=100, null=True, verbose_name='Who is reviewing it'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default='<name of place', max_length=200, verbose_name='Where are you reviewing'),
        ),
        migrations.AlterField(
            model_name='review',
            name='textfield',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='visitdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Visit'),
        ),
    ]
