# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-10 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abeona', '0003_auto_20180310_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('reviewerid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='<Reviewer>', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abeona.Reviewer'),
        ),
    ]
