# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-10 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abeona', '0004_auto_20180310_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPhotos',
            fields=[
                ('reviewphotoid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='<Reviewer>', max_length=20, null=True)),
                ('img', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('reviewid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abeona.Review')),
            ],
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='name',
            field=models.CharField(default='<Name of Reviewer>', max_length=20, verbose_name='Name of Reviewer'),
        ),
    ]
