# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-10 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abeona', '0005_auto_20180310_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='textfield',
        ),
    ]
