# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-10 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abeona', '0006_remove_review_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='textdata',
            field=models.TextField(null=True),
        ),
    ]
