# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-10 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abeona', '0008_review_googletag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='googletag',
        ),
        migrations.AddField(
            model_name='review',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
    ]
