# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abeona', '0009_auto_20180310_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('furnitureid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='<Item>', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('reviewitemid', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('furnitureid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abeona.Furniture')),
                ('reviewid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abeona.Review')),
            ],
        ),
    ]
