# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abeona', '0010_furniture_reviewitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewFurniture',
            fields=[
                ('reviewfurnitureid', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('furnitureid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abeona.Furniture')),
                ('reviewid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abeona.Review')),
            ],
        ),
        migrations.RemoveField(
            model_name='reviewitem',
            name='furnitureid',
        ),
        migrations.RemoveField(
            model_name='reviewitem',
            name='reviewid',
        ),
        migrations.DeleteModel(
            name='ReviewItem',
        ),
    ]
