# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abeona', '0011_auto_20180311_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('featureid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='<Item>', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewFeature',
            fields=[
                ('reviewfeatureid', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('featureid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abeona.Feature')),
                ('reviewid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abeona.Review')),
            ],
        ),
    ]
