# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abeona', '0013_auto_20180311_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewfurniture',
            name='furnitureid',
        ),
        migrations.RemoveField(
            model_name='reviewfurniture',
            name='reviewid',
        ),
        migrations.DeleteModel(
            name='Furniture',
        ),
        migrations.DeleteModel(
            name='ReviewFurniture',
        ),
    ]
