# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abeona', '0016_auto_20180311_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='placetype',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-visitdate',)},
        ),
        migrations.AlterModelOptions(
            name='reviewer',
            options={'ordering': ('name',)},
        ),
    ]
