# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 21:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abeona', '0017_auto_20180311_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('journalid', models.AutoField(primary_key=True, serialize=False)),
                ('entrydate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('textdata', models.TextField(null=True)),
                ('entryby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abeona.Reviewer')),
            ],
            options={
                'ordering': ('-entrydate',),
            },
        ),
        migrations.CreateModel(
            name='JournalPhoto',
            fields=[
                ('journalphotoid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='<Brief Description>', max_length=20, null=True)),
                ('img', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('journalid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abeona.Journal')),
            ],
        ),
        migrations.CreateModel(
            name='JournalTag',
            fields=[
                ('journaltagid', models.AutoField(primary_key=True, serialize=False)),
                ('journalid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abeona.Journal')),
            ],
            options={
                'ordering': ('journalid__name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='<Item>', max_length=20, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='journaltag',
            name='tagid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abeona.Tag'),
        ),
    ]
