# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 21:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abeona', '0018_auto_20180320_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journaltag',
            options={'ordering': ('journalid__entrydate',)},
        ),
    ]
