# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abeona', '0019_auto_20180320_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='entryby',
            new_name='enteredby',
        ),
    ]
